apiVersion: v1
kind: ReplicationController
metadata:
  name: alpine
spec:
  replicas: 1
  selector:
    app: alpine
  template:
    metadata:
      name: alpine
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: alpine:3.6
        command: [ "sleep", "36000" ]
